// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyTypeStats.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonkeyTypeStats.Api.Data.Migrations
{
    [DbContext(typeof(MonkeyTypeStatsDbContext))]
    partial class MonkeyTypeStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonkeyTypeStats.Api.Data.MonkeyTypeApiResponseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MonkeyTypeApiResponseLog");
                });

            modelBuilder.Entity("MonkeyTypeStats.Api.Data.Result", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Acc")
                        .HasColumnType("double precision");

                    b.Property<double?>("AfkDuration")
                        .HasColumnType("double precision");

                    b.Property<bool?>("BailedOut")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BlindMode")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("CharStats")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<double>("Consistency")
                        .HasColumnType("double precision");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string[]>("Funbox")
                        .HasColumnType("text[]");

                    b.Property<double?>("IncompleteTestSeconds")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsPb")
                        .HasColumnType("boolean");

                    b.Property<double>("KeyConsistency")
                        .HasColumnType("double precision");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("LazyMode")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mode2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Numbers")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Punctuation")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuoteLength")
                        .HasColumnType("integer");

                    b.Property<double>("RawWpm")
                        .HasColumnType("double precision");

                    b.Property<int?>("RestartCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<double>("TestDuration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Wpm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
